name: CI Pipeline (PRs and pushes main)
run-name: Merged to main by ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install package with pip
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run unit tests
        run: pytest